ALTER TABLE yardage
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;


INSERT INTO yardage (
  cost_per_yard,
  description,
  fabric_cost,
  finish_date,
  finished_length,
  labor_cost,
  lining_cost,
  lining_per_yard,
  panels,
  shop_supply_cost,
  start_date,
  title,
  total_width,
  total_yardage,
  width_per_panel,
  yardage_per_width,
  is_completed
)
VALUES (
  15.50,
  'Navy blue velvet fabric',
  310.00,
  '2024-03-15',
  20,
  150.00,
  50.00,
  2,
  5,
  25.00,
  '2024-01-10',
  'Custom Drapery',
  100,
  200,
  20,
  10,
  TRUE
);


